site_name: Tracepaper
docs_dir: './documentation'
site_dir: './docs'
site_url: 'http://localhost:8000'
base_url: 'http://localhost:8000'

theme:
  name: null
  custom_dir: mkdocs_windmill
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true

extra:
  history_buttons: false
  version: v3
