site_name: Tracepaper
docs_dir: './documentation'
site_dir: './docs'
site_url: 'https://tracepaper.draftsman.io/docs-twee'
base_url: './docs-twee'


theme:
  name: null
  custom_dir: mkdocs_windmill
  static_templates: [404.html]
  search_index_only: true
  include_search_page: true
  base_url: ./docs-twee

markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: false
  version: v3
