site_name: Tracepaper by Draftsman
docs_dir: './documentation'
site_dir: './docs'

theme:
  name: material
  custom_dir: material/overrides
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - announce.dismiss
    - privacy

